debug: false  # 디버그 로그 활성화 -> 너무 많아서 false
management.endpoints.web.exposure.include: "*"  #액츄에이터 활성화

logging:
  level:
    world.neverdie.livelong: debug  # 프로젝트 로그
    org.springframework.web.servlet: debug  # request, response 로그 보기
    org.hibernate.type.descriptor.sql.BasicBinder : trace #jpa 파라미터 로그
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklife
    username: jsh
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create #자동으로 ddl을 생성
    properties: #하이버네이트에서 사용하려는 설정 정의
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 #bulk select를 가능하게 해줌
    show-sql: true
  sql:
    init:
      mode: always
